# Generated by Django 6.0.1 on 2026-01-27 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activitytype",
            unique_together={("name",)},
        ),
        migrations.RemoveField(
            model_name="plan",
            name="user",
        ),
        migrations.RemoveField(
            model_name="activitytype",
            name="user",
        ),
    ]
